Curso: Kubernetes

Lecciones:
  Leccion1:
    Nombre: Introduccion
    Temas:
      - Contexto
      - Que es kubernetes
      - Arquitectura de Kubernetes
      - Casos de exito

  Leccion2:
    Nombre: Preparacion de entorno de trabajo
    Temas:
      - Descripcion minikube
      - Descripcion Kubectl
      - Descripcion kubeadm
      - Descripcion 
      - Instalar docker
      - Instalar kubectl
      - Instalar Minikube
      - Crear cluster minikube

  Leccion3:
    Nombre: Conceptos Basicos
    Temas:
      - Objects
        - Pods
        - Deployments
        - Services

  Leccion4:
    Nombre: Conceptos Intermedios
    Temas:
      - ClusterIp
      - NodePort
      - LoadBalancer

  Leccion5:
    Nombre: Conceptos avanzados
    Temas:
      - VolumeClaim
      - NodePort
      - LoadBalancer


DeployInCloud:
  - Manualmente
  - Utilizando el soporte para kubernetes. GKE 