Curso: Kubernetes

Lecciones:
  Leccion1:
    Nombre: Introduccion
    Temas:
      - Que es kubernetes
      - Arquitectura de un cluster k8
      - Casos de exito
      - Opinion Personal

  Leccion2:
    Nombre: Preparacion de entorno de trabajo
    Temas:
      - Descripcion minikube
      - Descripcion Kubectl
      - Descripcion kubeadm
      - Descripcion 
      - Instalar docker
      - Instalar kubectl
      - Instalar Minikube
      - Crear cluster minikube

  Leccion3:
    Nombre: Conceptos Basicos
    Temas:
      - Objects
      Imperative
        - Pods
        - ConfigMap
        - Secrets
        - Namespace
        - Services:
            - ClusterIp
            - NodePort
            - LoadBalancer



  Leccion4:
    Nombre: Conceptos Intermedios
    Temas:
    Config files
    Declarative
        - Deployments
        - DaemonSet
        - StatefulSet
        - ReplicaSet
        - Job


  Leccion5:
    Nombre: Conceptos avanzados
    Temas:
      - VolumeClaim
      - Ingress
      - Monitoring
      - Health checks


DeployInCloud:
  - Manualmente
  - Utilizando el soporte para kubernetes. GKE 